[package]
name = "ble-prodder"
version = "0.1.0"
edition = "2024"

[dependencies]
bluest = "0.6.9"
btleplug = "0.11.8"
eyre = "0.6.12"
futures = "0.3.31"
rand = "0.9.2"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
uuid = "1.19.0"
